# Generated by Django 3.1.2 on 2020-11-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellbeing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influence', models.IntegerField(default=None)),
                ('time', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='mood',
            name='mood_text',
        ),
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='mood',
            name='time',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=None),
        ),
        migrations.AddField(
            model_name='mood',
            name='value',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, 0), (1, 1)], default=None)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mood.person')),
            ],
        ),
        migrations.AddField(
            model_name='mood',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mood.person'),
        ),
    ]
