# Generated by Django 3.1.2 on 2020-11-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_auto_20201107_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_text',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
