# Generated by Django 3.1.3 on 2020-11-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_questions_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mood.questions'),
        ),
    ]
